version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=ms-notification
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - '27017:27017'
    networks:
      - MONGO
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    networks:
      - MONGO
    depends_on:
      - mongodb
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka-server:
    image: alpha4vit/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring
  apigw:
    image: alpha4vit/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
networks:
  MONGO:
    name: MONGO
  spring:
    driver: bridge

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG