spring:
  application:
    name: CustomerService
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-customer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    addresses: localhost:5672
server:
  servlet:
    context-path: /api/v1
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true