server:
  port: 8084
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/api/v1/customer/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true