spring:
  application:
    name: NotificationService
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: ms-notification
      username: rootuser
      password: rootpass
server:
  servlet:
    context-path: /api/v1
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key