spring:
  application:
    name: FraudService
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-fraud
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
server:
  servlet:
    context-path: /api/v1
  port: 8081